name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Build docker image
      run: docker build . -t app
    - name: Login into registry
      run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - name: Publish latest image
      run: |
        docker tag app "${IMAGE_NAME}:latest"
        docker push "${IMAGE_NAME}:latest"
      if: github.ref == "refs/heads/master"
    - name: Publish tagged image
      run: |
        echo "Ref: ${GITHUB_REF}"
        docker tag app "${IMAGE_NAME}:${GITHUB_REF##*/}"
        docker push "${IMAGE_NAME}:${GITHUB_REF##*/}"
      if: github.ref != "refs/heads/master"
    env:
      IMAGE_NAME: thewakingsands/cafemaker
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
